latest version deals with blank inputs and case

diff --git a/AddCust b/AddCust
--- a/AddCust
+++ b/AddCust
@@ -1,13 +1,20 @@
 #!/bin/bash
 #Add new customers to file CustomerDetails in the format
 #<E-mail Address>   <Name>   <Alias>   <Address>   <Telephone Number>
+# printf allow you to format the input of a print statment, in this case it formats the file CustomerDetails
 # check to see if CustomerDetails exists and if not then create it with the header
+clear
 if grep -q "Address" CustomerDetails 
 	then 
-	echo CustomerDetails already exits 
+	echo
+	echo CustomerDetails already exits
+
 else
+	echo
+	echo "Creating CustomerDetails file as none exists"
 	printf "\n%-30s %-8s %-8s %-20s %s" "<E-mail Address>" "<Name>" "<Alias>" "<Address>" "<Telephone Number>" >> CustomerDetails
 fi
+sleep 1
 clear
 # ANSI colour an formats moved to more readable variables names, can change echo colours
 # the NONE is to turn off the format, echo -e enables the colour, may not use all of these
@@ -30,30 +37,80 @@ echo -e " ${CYAN} / ___ \ (_| | (_| | |__| |_| \__ \ || (_) | | | | | |  __/ |  
 echo -e " ${CYAN}/_/   \_\__,_|\__,_|\____\__,_|___/\__\___/|_| |_| |_|\___|_|   ${NONE}"                                            
 echo -e ${CYAN}_________________________________________________________________ ${NONE}                                                           
 echo -e ${CYAN}_________________________________________________________________ ${NONE}
-echo Enter the following customer details 
+echo -e ${CYAN}Enter the following customer details ${NONE} 
 echo
-echo -e ${YELLOW}Name :${NONE}
+echo -e ${CYAN}Name :${NONE}
 read Name
+# -z checks variable Name to see if it is blank, if it is blank a message is printed 
+# will run a while loop until correct input all read statements are treated the same.
+while [ -z "$Name" ]
+do  
+    echo 
+	echo -e ${CYAN}"Invalid input blank spaces are not accepted"${NONE} 
+	echo
+	echo -e ${CYAN}Name :${NONE}
+	read Name
+done
 echo
-echo -e ${YELLOW}E-mail Address :${NONE}
+echo -e ${CYAN}E-mail Address :${NONE}
 read Email
+while [ -z "$Email" ]
+do  
+    echo 
+	echo -e ${CYAN}"Invalid input blank spaces are not accepted"${NONE} 
+	echo
+	echo -e ${CYAN}Email :${NONE}
+	read Email
+done
 echo
-echo -e ${YELLOW}Alias :${NONE}
+echo -e ${CYAN}Alias :${NONE}
 read Alias
+while [ -z "$Alias" ]
+do  
+    echo 
+	echo -e ${CYAN}"Invalid input blank spaces are not accepted"${NONE} 
+	echo
+	echo -e ${CYAN}Alias :${NONE}
+	read Alias
+done
 echo
-echo -e ${YELLOW}Address :${NONE}
+echo -e ${CYAN}Address :${NONE}
 read Address
+while [ -z "$Address" ]
+do  
+    echo 
+	echo -e ${CYAN}"Invalid input blank spaces are not accepted"${NONE} 
+	echo
+	echo -e ${CYAN}Address :${NONE}
+	read Address
+done
 echo
-echo -e ${YELLOW}Telephone Number :${NONE}
+echo -e ${CYAN}Telephone Number :${NONE}
 read Telephone
+while [ -z "$Telephone" ]
+do  
+    echo 
+	echo -e ${CYAN}"Invalid input blank spaces are not accepted"${NONE} 
+	echo
+	echo -e ${CYAN}Telephone :${NONE}
+	read Telephone
+done
 echo
+# following statment adds a new line to the end of the file CustomerDetails with the strings for the 
+# variables inputed above, printf has a formatting component 
+# \n new line
+# %-30s left justified ,place holder for 30 character string , other examples are similar 8 and 20 respectivly 
 printf "\n%-30s %-8s %-8s %-20s %s" "$Email" "$Name" "$Alias" "$Address" "$Telephone" >> CustomerDetails
 echo
-echo -e "${RED}Do you wish to return to the Menu ?(y/n)${NONE}" 
+# return to the Menu, anything entered other that y-Y including blank spaces will go to the else option and print message and exit to shell
+# entering y-Y and you meet the if condition and call the script for Menu
+echo -e "${RED}Enter 'y' to return to the Menu  ${NONE}"
+echo -e "${RED}Enter any other key to exit ${NONE}"
 read yesno
-if  [[ $yesno = "y" ]]
+if  [[ $yesno = "y" || $yesno = "Y" ]]
 	then 
 	  ./Menu
 else
 	echo Goodbye
+	exit 113
 fi
diff --git a/EmailCust b/EmailCust
--- a/EmailCust
+++ b/EmailCust
@@ -1,14 +1,22 @@
 #!/bin/bash
 #Email a customers from the file CustomerDetails 
 #Enter a customer email address to email
-# check to see if CustomerDetails exists and if not then create it with the header
+# check to see if CustomerDetails exists and contains a valid email address if not then redirect to AddCust to create it 
+# regex is explained further down on this page
+clear
 if grep -q "Address" CustomerDetails 
 	then 
 	echo CustomerDetails already exits 
+	sleep 1
+    clear
 else
+	echo
+	echo "Creating blank CustomerDetails file"
 	printf "\n%-30s %-8s %-8s %-20s %s" "<E-mail Address>" "<Name>" "<Alias>" "<Address>" "<Telephone Number>" >> CustomerDetails
+	sleep 1
+	clear
 fi
-clear
+
 # ANSI colour an formats moved to more readable variables names, can change echo colours
 # the NONE is to turn off the format, echo -e enables the colour, may not use all of these
 NONE='\033[00m'
@@ -31,63 +39,184 @@ echo -e "${RED}|_____|_| |_| |_|\__,_|_|_|\____\__,_|___/\__\___/|_| |_| |_|\___
 echo -e ${RED}________________________________________________________________________${NONE} 
 echo -e ${RED}________________________________________________________________________${NONE} 
 echo
-################################################################################################################
-# grep searches for a string that matches email format in file CustomerDetails  and outputs to temp file       #
-# -E switch allows uses of extended regular expression ERE                                                     #
-# -o switch only prints non empty parts of the string found i.e. no spaces                                     #
-# the search string has 4 parts                                                                                #
-# [A-Za-z0-9._%+-] any of the following characters can make up the string beteen [],                           #
-# letter a to z in upper and lower case ,numbers 0 to 9 and the following special characters ._%+-             #
-# +@ at is added to the first string                                                                           #
-# second string is the same as the first but only the following special characters .- include                  #
-# +\. adds a dot to the end of the second string                                                               #
-# [A-Za-z] last string letter a to z in upper and lower case                                                   #
-# {n,m}  The  preceding  item  is  matched  at  least n times, but not more than m times.                      #
-# >> use standard output to a temp file                                                                        #
-# The symbol \b matches the empty string at the edge of a word , in this case at the beginning and the end     #
-################################################################################################################
-grep -E -o "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b" CustomerDetails >> temp
-# prompt user to see if they want to send a group mail
-echo "Do you wish to send an email everyone ? (y/n)"
-# waiting for response at prompt and passing value to variable "everyone"
-read everyone
-# if statment to check to see if variable "everyone" is set to y, if not go to else statment
-if [[ $everyone = "y" ]]
+# the following if statement enclosed entire mail script , it checks to see if there is a valid email address in CustomerDetails
+# if not it jumps to the end of the script
+if grep -q -E -o "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b" CustomerDetails
 	then
-	# prompt and wait for responce for subject and message body
-	echo Subject:
-	read Subject
-	echo Message body:
-	read Message
-	# echo the message and pipe it to the mailx command -s is the subject switch and 
-	# then you put in the email address in this case we are pulling the mail address from the temp file
-	# mailutils needs to be installed for this to work "sudo apt-get install mailutils"
-	echo "$Message" | mailx -s "$Subject" $(<temp)
-	# this echo is just to show that the command above has completed , it doesn't gurantee delivery
-	echo message sent
+	################################################################################################################
+	# grep searches for a string that matches email format in file CustomerDetails  and outputs to temp file       #
+	# -E switch allows uses of extended regular expression ERE                                                     #
+	# -o switch only prints non empty parts of the string found i.e. no spaces                                     #
+	# the search string has 4 parts                                                                                #
+	# [A-Za-z0-9._%+-] any of the following characters can make up the string beteen [],                           #
+	# letter a to z in upper and lower case ,numbers 0 to 9 and the following special characters ._%+-             #
+	# +@ at is added to the first string                                                                           #
+	# second string is the same as the first but only the following special characters .- include                  #
+	# +\. adds a dot to the end of the second string                                                               #
+	# [A-Za-z] last string letter a to z in upper and lower case                                                   #
+	# {n,m}  The  preceding  item  is  matched  at  least n times, but not more than m times.                      #
+	# >> use standard output to a temp file                                                                        #
+	# The symbol \b matches the empty string at the edge of a word , in this case at the beginning and the end     #
+	################################################################################################################
+	grep -E -o "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b" CustomerDetails >> temp
+	# prompt user to see if they want to send a group mail
+	echo -e ${RED}"Enter 'y' to send an email everyone"${NONE}
+	echo -e ${RED}"Enter any other key to skip mass email "${NONE}
+	# waiting for response at prompt and passing value to variable "everyone"
+	read everyone
+	# if statment to check to see if variable "everyone" is set to y-Y, if yes proceed with mass email send to all customer
+	# if not go to else statment which search for an individual email address and sends to that email address 
+	if [[ $everyone = "y" || $everyone = "Y" ]]
+		then
+		# prompt and wait for responce for subject and message body
+		echo -e ${RED}"Subject:"${NONE}
+		read Subject
+		# -z checks for blank input, while will continue to check if input blank, the same checks are applied to Message
+		while [ -z "$Subject" ]
+	    do  
+	        echo 
+		    echo -e ${RED}"Invalid input blank spaces are not accepted"${NONE}
+			echo
+			echo -e ${RED}"Subject:"${NONE}
+			read Subject
+		done
+		echo -e ${RED}Message body:${NONE}
+		read Message
+		while [ -z "$Message" ]
+	    do  
+	        echo 
+		    echo -e ${RED}"Invalid input blank spaces are not accepted"${NONE}
+			echo
+			echo -e ${RED}"Message:"${NONE}
+			read Message
+		done
+		# echo the message and pipe it to the mailx command -s is the subject switch and 
+		# then you put in the email address in this case we are pulling the mail address from the temp file
+		# mailutils needs to be installed for this to work "sudo apt-get install mailutils"
+		echo "$Message" | mailx -s "$Subject" $(<temp)
+		# this echo is just to show that the command above has completed , it doesn't gurantee delivery
+		echo -e ${RED}message sent${NONE}
+	else	
+		echo -e ${RED}Enter details of customer you wish to email:${NONE}
+    	read details 
+    	# -z checks for blank input , loop until something is entered for details
+    	while [ -z "$details" ]
+    	do  
+        	echo 
+	    	echo -e ${RED}"Invalid input blank spaces are not accepted"${NONE}
+			echo
+			echo -e ${RED}"Enter details of customer you wish to email: "${NONE}
+			read details
+		done
+		# uses grep -c to get a number of matching searches for the string details in CustomerDetails then displays results
+		count=`grep -c $details CustomerDetails`
+    	echo
+		echo -e ${RED}"There are "$count" contacts found matching your search"${NONE}
+		echo
+		echo -e ${RED}================================================================================${NONE}
+		echo
+		grep -i $details CustomerDetails
+		echo
+		echo -e ${RED}================================================================================${NONE}
+		echo
+		# if count is greater that 1 , narrow down the search by asking the user for more exact details
+		if [[ $count -gt 1 ]]
+			then
+	    	echo -e ${RED}"Enter details of email address to narrow the search"${NONE}
+	    	read details
+	    	# use -z again to check for blank input
+	    	while [ -z "$details" ]
+			do  
+	    		echo 
+				echo -e ${RED}"Invalid input blank spaces are not accepted"${NONE}
+				echo
+				echo -e ${RED}Enter the Name or Alias of the customer delete :${NONE}
+				read details
+			done
+			echo
+			# new grep search on new input
+			echo -e ${RED}"Refined search results"${NONE}
+			echo
+			echo -e ${RED}================================================================================${NONE}
+			echo
+			grep -i $details CustomerDetails
+			echo
+			echo -e ${RED}================================================================================${NONE}
+		fi
+		# search temp file (use temp as CustomerDetails has a header which awk would detect) 
+		# for line contain details varable and let the first thing on that line equal Email
+		Email=`grep -i "$details" temp | awk '{print $1}'`
+			# if Email is blank , displays message and lists CustomerDetails and asks for imput again
+		    while [ -z "$Email" ] 
+			do
+				echo
+				echo -e ${RED}"Contact not found "${NONE}
+				echo
+				# contacts listed by concating the file CustomerDetails
+				echo -e ${RED}"List of contacts in the CustomerDetails file"${NONE}
+				echo
+				echo -e ${RED}================================================================================${NONE}
+				cat CustomerDetails
+				echo
+				echo
+				echo -e ${RED}================================================================================${NONE}
+				echo
+				echo
+				echo -e ${RED}Enter details of customer you wish to email:${NONE}
+				read details
+				# -z checks for blank input
+				while [ -z "$details" ]
+	            do  
+	    		    echo 
+		    		echo -e ${RED}"Invalid input blank spaces are not accepted"${NONE}
+					echo
+					echo -e ${RED}"Enter details of customer you wish to email: "${NONE}
+					read details
+				done
+				Email=`grep -i "$details" temp | awk '{print $1}'`
+			done
+		echo	
+		echo -e ${RED}"Email address : "${NONE} 
+		echo $Email
+		echo
+		echo -e ${RED}"Subject:"${NONE}
+		read Subject
+		while [ -z "$Subject" ]
+	    do  
+	        echo 
+		    echo -e ${RED}"Invalid input blank spaces are not accepted"${NONE}
+			echo
+			echo -e ${RED}"Subject:"${NONE}
+			read Subject
+		done
+		echo -e ${RED}Message body:${NONE}
+		read Message
+		while [ -z "$Message" ]
+	    do  
+	        echo 
+		    echo -e ${RED}"Invalid input blank spaces are not accepted"${NONE}
+			echo
+			echo -e ${RED}"Message:"${NONE}
+			read Message
+		done
+		echo "$Message" | mailx -s "$Subject" "$Email"
+		echo -e ${RED}message sent${NONE}
+		# remove the temp file
+	    rm temp
+    fi
 else
-	echo Enter email address:
-	read Email
-	echo Subject:
-	read Subject
-	echo Message body:
-	read Message
-	echo "$Message" | mailx -s "$Subject" "$Email"
-	echo message sent
+	echo -e ${RED}"CustomerDetails doesn't contain any valid email address"${NONE}
 fi
-# remove the temp file
-rm temp
 echo
-echo -e "${RED}Do you wish to return to the Menu ?(y/n) ${NONE}"
+# return to the Menu, anything entered other that y-Y including blank spaces will go to the else option and end the script
+# entering y-Y and you meet the if condition and call the script for Menu
+echo -e "${RED}Enter 'y' to return to the Menu ${NONE}"
+echo -e "${RED}Enter any other key to exit ${NONE}"
 read yesno
-if  [[ $yesno = "y" ]]
+if  [[ $yesno = "y" || $yesno = "Y" ]]
 	then 
 	  ./Menu
 else
 	echo Goodbye
+	exit 113
 fi
-
-
-
-
-
diff --git a/FindCust b/FindCust
--- a/FindCust
+++ b/FindCust
@@ -1,52 +1,72 @@
 #!/bin/bash
 #find an existing customers from the file CustomerDetails 
 #Enter a customer detail to find a contact
-# check to see if CustomerDetails exists and if not then create it with the header
+# check to see if CustomerDetails exists and if not then print warning and recommended action
+clear
 if grep -q "Address" CustomerDetails 
 	then 
-	echo CustomerDetails already exits 
+	echo -e ${YELLOW}CustomerDetails already exits ${NONE} 
+	sleep 1
+    clear
+    	# ANSI colour an formats moved to more readable variables names, can change echo colours
+	# the NONE is to turn off the format, echo -e enables the colour, may not use all of these
+	NONE='\033[00m'
+	RED='\033[01;31m'
+	GREEN='\033[01;32m'
+	YELLOW='\033[01;33m'
+	BLUE='\033[01;34m'
+	PURPLE='\033[01;35m'
+	CYAN='\033[01;36m'
+	WHITE='\033[01;37m'
+	BOLD='\033[1m'
+	UNDERLINE='\033[4m'
+	echo 
+	echo -e ${BLUE}__________________________________________________________________${NONE} 
+	echo -e "${BLUE} _____ _           _  ____          _                            ${NONE}"
+	echo -e "${BLUE}|  ___(_)_ __   __| |/ ___|   _ ___| |_ ___  _ __ ___   ___ _ __ ${NONE}"
+	echo -e "${BLUE}| |_  | | '_ \ / _' | |  | | | / __| __/ _ \| '_ ' _ \ / _ \ '__|${NONE}"
+	echo -e "${BLUE}|  _| | | | | | (_| | |__| |_| \__ \ || (_) | | | | | |  __/ |   ${NONE}"
+	echo -e "${BLUE}|_|   |_|_| |_|\__,_|\____\__,_|___/\__\___/|_| |_| |_|\___|_|   ${NONE}"                                                              
+	echo -e ${BLUE}__________________________________________________________________${NONE} 
+	echo -e ${BLUE}__________________________________________________________________${NONE} 
+	echo
+	echo -e ${BLUE}"What do you want to search for:"${NONE} 
+	read search
+	# -z checks variable Name to see if it is blank, if it is blank a message is printed and the script restarted
+	while [ -z "$search" ]
+	do  
+	    echo 
+		echo -e ${BLUE}"Invalid input blank spaces are not accepted"${NONE} 
+		echo
+		echo -e ${BLUE}"What do you want to search for:"${NONE} 
+		read search
+	done
+	echo
+	# grep does a count of the successful matches to the string search in CustomerDetails
+	# Which is then applied to a varalable count, we then print out the result
+	count=`grep -c $search CustomerDetails`
+	echo -e ${BLUE}"There are "$count" contacts found matching your search"${NONE} 
+	echo
+	# grep searches for a string in the varable search in CustomerDetails file the -i ignors the case
+	echo -e ${BLUE}=======================================================================================${NONE} 
+	echo
+	grep -i $search CustomerDetails
+	echo
+	echo -e ${BLUE}=======================================================================================${NONE} 
+	echo
 else
-	printf "\n%-30s %-8s %-8s %-20s %s" "<E-mail Address>" "<Name>" "<Alias>" "<Address>" "<Telephone Number>" >> CustomerDetails
+	echo -e ${YELLOW}"Find Customer script can't find custusomers as CustomerDetails file is empty"${NONE} 
+	echo -e ${YELLOW}"Go to Add Customer to create some contacts"${NONE} 
 fi
-clear
-# ANSI colour an formats moved to more readable variables names, can change echo colours
-# the NONE is to turn off the format, echo -e enables the colour, may not use all of these
-NONE='\033[00m'
-RED='\033[01;31m'
-GREEN='\033[01;32m'
-YELLOW='\033[01;33m'
-BLUE='\033[01;34m'
-PURPLE='\033[01;35m'
-CYAN='\033[01;36m'
-WHITE='\033[01;37m'
-BOLD='\033[1m'
-UNDERLINE='\033[4m'
-echo 
-echo -e ${BLUE}__________________________________________________________________${NONE} 
-echo -e "${BLUE} _____ _           _  ____          _                            ${NONE}"
-echo -e "${BLUE}|  ___(_)_ __   __| |/ ___|   _ ___| |_ ___  _ __ ___   ___ _ __ ${NONE}"
-echo -e "${BLUE}| |_  | | '_ \ / _' | |  | | | / __| __/ _ \| '_ ' _ \ / _ \ '__|${NONE}"
-echo -e "${BLUE}|  _| | | | | | (_| | |__| |_| \__ \ || (_) | | | | | |  __/ |   ${NONE}"
-echo -e "${BLUE}|_|   |_|_| |_|\__,_|\____\__,_|___/\__\___/|_| |_| |_|\___|_|   ${NONE}"                                                              
-echo -e ${BLUE}__________________________________________________________________${NONE} 
-echo -e ${BLUE}__________________________________________________________________${NONE} 
-echo
-echo "what do you want to search for:"
-read search
-echo
-echo ================================================================================
-echo
-grep $search CustomerDetails
-echo
-echo ================================================================================
-echo
-echo -e "${RED}Do you wish to return to the Menu ?(y/n) ${NONE}"
+# return to the Menu, anything entered other that y-Y including blank spaces will go to the else option and end the script
+# entering y-Y and you meet the in condition and call the script for Menu
+echo -e "${RED}Enter 'y' to return to the Menu ${NONE}"
+echo -e "${RED}Enter any other key to exit ${NONE}"
 read yesno
-if  [[ $yesno = "y" ]]
+if  [[ $yesno = "y" || $yesno = "Y" ]]
 	then 
 	  ./Menu
 else
 	echo Goodbye
-fi                                                          
-
-
+	exit 113
+fi
diff --git a/RemCust b/RemCust
--- a/RemCust
+++ b/RemCust
@@ -2,12 +2,15 @@
 #remove existing customers from the file CustomerDetails 
 #Enter either <Name> or <Alias> to remove
 # check to see if CustomerDetails exists and if not then create it with the header
+clear
 if grep -q "Address" CustomerDetails 
 	then 
 	echo CustomerDetails already exits 
 else
+    echo "Creating CustomerDetails file as none exists"
 	printf "\n%-30s %-8s %-8s %-20s %s" "<E-mail Address>" "<Name>" "<Alias>" "<Address>" "<Telephone Number>" >> CustomerDetails
 fi
+sleep 1
 clear
 # ANSI colour an formats moved to more readable variables names, can change echo colours
 # the NONE is to turn off the format, echo -e enables the colour, may not use all of these
@@ -31,29 +34,83 @@ echo -e "${PURPLE}|_| \_\___|_| |_| |_|\___/ \_/ \___|\____\__,_|___/\__\___/|_|
 echo -e ${PURPLE}_______________________________________________________________________________ ${NONE}
 echo -e ${PURPLE}_______________________________________________________________________________ ${NONE}
 echo
-echo Enter the Name or Alias of the customer delete :
+echo -e ${PURPLE}Enter the Name or Alias of the customer delete :${NONE}
 read Name
+# -z checks variable Name to see if it is blank, if it is blank a message is printed and the script restarted
+while [ -z "$Name" ]
+do  
+    echo 
+	echo -e ${PURPLE}"Invalid input blank spaces are not accepted"${NONE}
+	echo
+	echo -e ${PURPLE}Enter the Name or Alias of the customer delete :${NONE}
+	read Name
+done
+# grep does a count of the successful matches to the string Name in CustomerDetails
+# Which is then applied to a varalable count, we then print out the result
+count=`grep -c $Name CustomerDetails`
 echo
-echo ================================================================================
+echo -e ${PURPLE}"There are "$count" contacts found matching your search"${NONE}
 echo
-grep $Name CustomerDetails
+# grep searches for a string in the varable Name in CustomerDetails file the -i ignors the case
+echo -e ${PURPLE}=======================================================================================${NONE}
 echo
-echo ================================================================================
-echo "Please confirm you wish to delete (y/n):"
-read confirm
-if [[ $confirm = 'y' ]]
+grep -i $Name CustomerDetails
+echo
+echo -e ${PURPLE}=======================================================================================${NONE}
+echo
+# if count is greater that 1 , narrow down the search by asking the user for more exact details
+if [[ $count -gt 1 ]]
 	then
-	# searches for the string in the Name variable and deletes the line it is on
-	sed -i "/$Name/d" CustomerDetails
-	echo Customer deleted
+    echo -e ${PURPLE}"Enter exact name to narrow the search"${NONE}
+    read Name
+    # use -z again to check for blank input
+    while [ -z "$Name" ]
+	do  
+    	echo 
+		echo -e ${PURPLE}"Invalid input blank spaces are not accepted"${NONE}
+		echo
+		echo -e ${PURPLE}Enter the Name or Alias of the customer delete :${NONE}
+		read Name
+	done
+	echo
+	# new grep search on new input
+	echo -e ${PURPLE}"Refined search results"${NONE}
+	echo
+	echo -e ${PURPLE}=======================================================================================${NONE}
+	echo
+	grep -i $Name CustomerDetails
+	echo
+	echo -e ${PURPLE}=======================================================================================${NONE}
+fi
+# if the count is equal to zero then display message no contact exists
+if [ $count = 0 ]
+   	then
+   	echo
+   	echo -e ${PURPLE}"No contact exists"${NONE}
+else 
+	# else confirm that you wish to delete the results of the last search
+	# anything entered other that y-Y including blank spaces will skip the delete
+    echo  	
+	echo -e ${PURPLE}"Please enter 'y' to confirm you wish to delete "${NONE}
+	echo -e ${PURPLE}"Enter any other key to skip delete "${NONE}
+	read confirm
+	if [[ $confirm = 'y' || $confirm = 'Y' ]]
+		then
+		# searches for the string in the Name variable and deletes the line it is on
+		sed -i "/$Name/d" CustomerDetails
+		echo -e ${PURPLE}Customer deleted${NONE}
+	fi
 fi
 echo
-echo -e "${RED}Do you wish to return to the Menu ?(y/n) ${NONE}"
+# return to the Menu, anything entered other that y-Y including blank spaces will go to the else option and end the script
+# entering y-Y and you meet the if condition and call the script for Menu
+echo -e "${RED}Enter 'y' to return to the Menu ${NONE}"
+echo -e "${RED}Enter any other key to exit ${NONE}"
 read yesno
-if  [[ $yesno = "y" ]]
+if  [[ $yesno = "y" || $yesno = "Y" ]]
 	then 
 	  ./Menu
 else
 	echo Goodbye
+	exit 113
 fi
-
